# Generated by Django 3.0.6 on 2020-07-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=50)),
                ('related_feature_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='Values',
        ),
        migrations.AddField(
            model_name='feature',
            name='choice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tokenization.Value'),
        ),
    ]
