# Generated by Django 3.0.6 on 2020-07-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0002_auto_20200706_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='choice',
        ),
    ]
