# Generated by Django 3.0.6 on 2020-07-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0003_remove_feature_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='choice',
            field=models.ManyToManyField(to='tokenization.Value'),
        ),
    ]
