# Generated by Django 3.0.6 on 2020-07-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0004_feature_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='choice',
            new_name='values',
        ),
    ]
