# Generated by Django 3.0.6 on 2020-07-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenization', '0005_auto_20200715_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('features', models.ManyToManyField(to='tokenization.Feature')),
            ],
        ),
    ]
